taskTracker/lib/taskTracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  def get_current_user(conn, params) do
    user_id = get_session(conn, :user_id)
    if user_id do
      user = TaskTracker.Accounts.get_user!(user_id)
      assign(conn, :current_user, user)
    else
      assign(conn, :current_user, nil)
    end
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/tasklist", PageController, :tasklist

    resources "/users", UserController
    resources "/task", TaskController

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

taskTracker/lib/taskTracker_web/templates/page/index.html.eex
<div class="row">
  <div class="col">
    <h1> TaskTracker </h1>
    <%= form_tag("/session", method: :post) do %>
      <div class="form-group">
        Email
        <input type="email" name="email" placeholder="xx@example.com">
      </div>
      <div class="form-group">
        <button class="btn btn-primary">Log In</button>
        <%= link "Register", to: user_path(@conn, :new) %>
      </div>
    <% end %>
  </div>
</div>

taskTracker/lib/taskTracker_web/templates/page/tasklist.html.eex
<%= if @current_user do %>
<div class="row">
  <div class="col">
    <%= render TaskTrackerWeb.TaskView, "form.html", Map.put(assigns, :action, task_path(@conn, :create)) %>
  </div>
</div>
<% end %>


<h1>Your Tasks</h1>
<div class="table">
<div class="row">
  <div class="col">
    <strong>User</strong>
  </div>
  <div class="col">
    <strong>Title</strong>
  </div>
  <div class="col">
    <strong>Description</strong>
  </div>
  <div class="col">
    <strong>Completed</strong>
  </div>
  <div class="col">
    <strong>Minutes</strong>
  </div>
  <div class="col">
  </div>
</div>
<%= Enum.map @tasks, fn task -> %>
<div class="row">
  <div class="col">
    <%= task.user.name %>
  </div>
  <div class="col">
    <%= task.title %>
  </div>
  <div class="col">
    <%= task.description %>
  </div>
  <div class="col">
    <%= task.completed %>
  </div>
  <div class="col">
    <%= task.minutes %>
  </div>
  <div class="col">
    <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
    <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
    <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
  </div>
</div>
<% end %>
</div>